
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin_test
      POSTGRES_USER: admin_test
    ports:
      - "6543:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 12080:8080