
version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: pg.dockerfile
    image: "postgres_img"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      PGDATA: ${DB_DATA}
    ports:
      - "6543:5432"
    env_file:
      - .env
    volumes: 
      - skaveor:/data/skaveor
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 12080:8080
      
volumes:
    skaveor:
      #external: true